### ISSUE TITLE
Add brief information on quantpendia

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio-docs#109]
Describe when we might not be able to run tximport. These remain available as quant files. Note that these can be downloaded via the quantpendium. Also link to the API docs in case someone wants to use the API.

**Comment by jaclyn-taroni** [comment]
We will also likely need to include a new illustration that contains information about the folder structure of the download folks will receive cc: @dvenprasad

**Comment by dvenprasad** [comment]
![docs-downloads-rna-seq-compendia](https://user-images.githubusercontent.com/15315514/65271488-4289af00-daeb-11e9-9006-2d7536c4a103.png)

spoke with @arielsvn and the download folder name include the species.
