### ISSUE TITLE
Use case examples for docs

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#11]
Chatted a bit with @dvenprasad about this, but wanted to open this up for discussion with @cgreene. Given that we have a limited amount of time, we'll need to prioritize which _kinds of_ use cases (related: https://github.com/AlexsLemonade/refinebio/issues/97) we'll put together. Specifically, we think the users that would most benefit from some examples initially) are biology experts and folks with a background in machine learning with less biology knowledge. With that in mind, here are three examples I am considering:

* Downloading a single experiment and using it with [Gene Pattern Notebooks](http://genepattern-notebook.org) for something like clustering (see [public examples](http://genepattern-notebook.org/public-notebooks/); login required to go beyond that page). I believe this may have a lower barrier to entry than some R snippets, but this could use a bit more research.
* Analyzing a collection of data with a neural network based model like [Tybalt](https://github.com/greenelab/tybalt). I'm a bit concerned about the optimization that would be required here.
* Some kind of (relatively simple) cross-species example that includes ortholog mapping (most likely with [hcop](https://github.com/stephenturner/hcop)). This along the lines of **use case eight** [here](
https://github.com/AlexsLemonade/refinebio/issues/97#issuecomment-363783331).

**Comment by cgreene** [comment]
I defer to you on the utility of Gene Pattern Notebooks (just not familiar enough with them). I wonder if we want to focus primarily on the type of bio-focused users that we expect at the start (simple things, like differential expression analysis, etc) than the ML folks. That seems like the most important set of things to get up first to me.

**Comment by jaclyn-taroni** [comment]
We could potentially do simple things like differential expression and clustering multiple ways, too.

**Comment by jaclyn-taroni** [comment]
GenePattern modules typically require GCT format. The [GenePattern documentation](http://software.broadinstitute.org/cancer/software/genepattern/file-formats-guide#GCT) has helpful information about GCT format. We can point users there and/or provide a code snippet.

**Comment by jaclyn-taroni** [comment]
Also need a [CLS file](http://software.broadinstitute.org/cancer/software/genepattern/file-formats-guide#CLS) if doing differential expression analysis.

**Comment by jaclyn-taroni** [comment]
Related: AlexsLemonade/refinebio#333

**Comment by jaclyn-taroni** [comment]
I think this is better tracked elsewhere, so I'm going to close this.
