### ISSUE TITLE
Add note about collapsing compendia based on genus

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#116]
https://github.com/AlexsLemonade/refinebio/issues/1736#issuecomment-540643437

**Comment by dvenprasad** [comment]
The section will need to include the list mentioned in https://github.com/AlexsLemonade/refinebio/issues/1736#issuecomment-540643437

**Comment by jaclyn-taroni** [comment]
While I am at it, I'm also going to change the `Download Folder` headers under the two types of compendia so that they are not the same.
