### ISSUE TITLE
Notes from @jaclyn-taroni and @dvenprasad pairing

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#12]
#### Reordering the documentation
1. Source Data
2. Processing information
  i. Aggregation
  ii. Transformation
3. Downloadable files

#### Illustration notes
- ~Source data repositories -> refine.bio~
- ~An illustration of what to expect in zip files would go under downloadable files section (circle back after poking around staging data)~
- ~Illustration of inner join and outer join ("typical" aggregation and species compendia aggregation, respectively)~
- ~Pipeline diagrams from processing modals: RNA-seq, microarray (@dvenprasad will export)~
- ~refine.bio processed and submitter processed badges (@dvenprasad will export)~
- ~Plots that show gene expression values before and after transformations (z-score, zero to one, possibly QN) - @jaclyn-taroni will make plots as a starting point~
- ~Maybe a metadata smoothing / corrected values illustration - see this table: 
https://github.com/AlexsLemonade/refinebio/pull/252#issuecomment-390286190~
- Maybe for identifier refinery? Filtering that occurs

#### Screenshots
- Dropdown menus (aggregation, transformations)
- "Where can I find information about software versions?" -> processing information modals

**Comment by jaclyn-taroni** [comment]
Put table from https://github.com/AlexsLemonade/refinebio/pull/252#issuecomment-390286190 into the documentation

**Comment by jaclyn-taroni** [comment]
Reordering was covered by #14

**Comment by dvenprasad** [comment]
Illustrations (draft) - for reference
![img_20180820_144054](https://user-images.githubusercontent.com/15315514/44425306-75b0e600-a559-11e8-829d-93eec66400a2.jpg)

**Comment by dvenprasad** [comment]
Inner Join:

![inner join](https://user-images.githubusercontent.com/15315514/44533144-dc9dde80-a6c2-11e8-8764-4dce4c4bf54e.png)


Outer Join:

![outer join](https://user-images.githubusercontent.com/15315514/44533494-a3b23980-a6c3-11e8-892a-8d6e56cd1207.png)

Repos to refine.bio:

![funnel](https://user-images.githubusercontent.com/15315514/44533218-08b95f80-a6c3-11e8-9eb8-827086fd2d99.png)


I'm working on the illustration for harmonized metadata.

**Comment by jaclyn-taroni** [comment]
Awesome, thanks! I'll start dropping these in

**Comment by jaclyn-taroni** [comment]
@dvenprasad I think there's an issue with spacing in `Sample 1 Gene Expression` in the inner join illustration

**Comment by jaclyn-taroni** [comment]
And should be `Aggregated Gene Expression Matrix`

**Comment by dvenprasad** [comment]
I updated the images in my comment above. ☝️

**Comment by dvenprasad** [comment]
Harmonized metadata:

![harmonized-metadata](https://user-images.githubusercontent.com/15315514/44549202-5eefc800-a6ee-11e8-8a7b-57826f0153f2.png)


Exports:
- Badges

**Comment by dvenprasad** [comment]
Download Folder structures:
![docs-downloads-species-agg](https://user-images.githubusercontent.com/15315514/45906715-2f9eaa80-bdc3-11e8-8ab3-90ccc40cfa11.png)
![docs-downloads-experiment-agg](https://user-images.githubusercontent.com/15315514/45906716-2f9eaa80-bdc3-11e8-9855-2aaeb74e588d.png)


Questions about QN illustration: 
- For the before and after plots, what are the labels for the axes? 
- Which platform are we using to calculate the reference distribution?

**Comment by jaclyn-taroni** [comment]
Thanks for the illustration @dvenprasad !

To answer your QN questions:
> For the before and after plots, what are the labels for the axes?

x-axis is **expression value**, y-axis is **density**

> Which platform are we using to calculate the reference distribution?

The _specific_ platform depends on the organism. It will be the most popular microarray platform that we can process from raw for that organism.

Let me know if you need anything else!

**Comment by dvenprasad** [comment]
Here are the illustrations for QN:

![docs-ref-dist](https://user-images.githubusercontent.com/15315514/45969124-cb692a00-c000-11e8-9cfc-6317c92202c8.png)


![docs-normalization](https://user-images.githubusercontent.com/15315514/45969127-cefcb100-c000-11e8-930c-66aa4177f79e.png)

**Comment by jaclyn-taroni** [comment]
The only thing left on this ticket is now tracked on #43
