### ISSUE TITLE
Compendia Does Not Include Submitter Processed Samples

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/refinebio-docs#130]
When the changes in https://github.com/AlexsLemonade/refinebio/pull/2148 are merged will be no longer including submitter processed data in any of the compendia. It is my opinion that the docs already convey this but perhaps it could make it more explicit. 

>refine.bio normalized compendia are comprised of all the samples from a species that we were able to process, aggregate, and normalize. Normalized compendia provide a snapshot of the most complete collection of gene expression that refine.bio can produce for each supported organism. We process these compendia in a manner that is different from the options that are available via the web user interface.

Would it make sense to add a line that says something to the effect of:

> [Submitter processed](#submitter-processed-submitter-processed-badge) samples that are available through the web user interface are omitted from normalized compendia.

Maybe also add a line saying why or a link to the [issue](https://github.com/AlexsLemonade/refinebio/issues/2114) that brought it to our attention.

**Comment by jaclyn-taroni** [comment]
I agree that we should make it explicit when we make that change. My read of what is currently there is not that submitter processed data is excluded because I would consider what we do to submitter processed data to fall under
> process, aggregate, and normalize. 

where "process" is pretty much limited to identifier mapping. This is why explicit is good!
