### ISSUE TITLE
Add information about obtaining Salmon transcriptome indices

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#17]

**Comment by jaclyn-taroni** [comment]
For reference: https://github.com/AlexsLemonade/refinebio/pull/363

**Comment by kurtwheeler** [comment]
Ok so at the moment we aren't doing much more than just putting the transcriptome indices in this S3 bucket: https://s3.console.aws.amazon.com/s3/buckets/data-refinery-s3-transcriptome-index-circleci-staging/?region=us-east-1&tab=overview

Unfortunately that bucket isn't set to public-read yet. I'm changing it in a branch, but until that gets applied you won't be able to see what the contents look like. However I've screenshotted the current bucket from staging:
![image](https://user-images.githubusercontent.com/4026833/44472004-3509a900-a5fb-11e8-952c-d3b525214985.png)

So once I clear up the permissions for that bucket, it will be possible to direct users there so they can go through and find the one they're looking for. However by the time we're in beta we will have two of them for every organism, so looking through them all will be painful. However our API can make this easier!

https://api.staging.refine.bio/transcriptome_indices/?organism=DANIO_RERIO&length=LONG

If you click that link you'll see that there's an s3_url field. You can use that to download the index tarball! Even though the bucket itself isn't open to the public, all of the objects in it are.

I will note that using the API to make that query is not the best user experience. At some point when we have the bandwidth it might be good to have a page or something dedicated to this @dvenprasad
