### ISSUE TITLE
Readthedocs doesn't support markdown tables

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio-docs#29]
https://github.com/rtfd/readthedocs.org/issues/2941

and 

https://github.com/rtfd/recommonmark/issues/3

Looks like we might need to change our metadata harmonization table into something else. One idea that comes to mind is taking a screenshot of what's on the github and using that, but this solution seems horribly unmaintainable.

**Comment by jaclyn-taroni** [comment]
![harmony-table](https://user-images.githubusercontent.com/19534205/44610986-ea3f8b00-a7cc-11e8-9a4c-49ba9ecb5278.png)
<img src="https://user-images.githubusercontent.com/19534205/44610997-f592b680-a7cc-11e8-98c7-e9eac81d8892.png" width="296" >

**Comment by jaclyn-taroni** [comment]
Found this in the second issue you linked there: https://pypi.org/project/sphinx-markdown-tables/

**Comment by jaclyn-taroni** [comment]
Doesn't look like this was resolved by #32 even though I was able to get it working locally

**Comment by jaclyn-taroni** [comment]
Wooohoooo I think #35 did it!

**Comment by cgreene** [comment]
Yay! 🎉
