### ISSUE TITLE
Update processing modal screenshot 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#43]
The processing modal screenshot we have will be out of date, so we should include a new one.
Related: https://github.com/AlexsLemonade/refinebio-frontend/issues/293

**Comment by dvenprasad** [comment]
![2018-10-01 16 29 38](https://user-images.githubusercontent.com/15315514/46314077-92e4c580-c597-11e8-9aff-5f8baeca763b.gif)

**Comment by dvenprasad** [comment]
closed via #54
