### ISSUE TITLE
Docs Aren't Friendly // Add Introduction

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-docs#55]
There's no friendly introduction to the documentation explain what this is all about. It's not what I expected to find when exploring the documentation.

**Comment by jaclyn-taroni** [comment]
Can you be more specific? Any links to examples where you feel this is done well would be much appreciated. Thanks!

**Comment by Miserlou** [comment]
Kenny uses writes pretty good docs pages: http://docs.python-tablib.org/en/latest/

Usage example, mission/philosophy, basic usage, advanced usage, contributing, support.

**Comment by dvenprasad** [comment]
Maybe we could organize it like this: 
- Describe refine.bio and what someone can do with it (i.e search and download data)
- Who/What is it for?
  - Link to example use cases
- Who/What is it NOT for?
- List of FAQs (Pick the top 5) 
- Contents (if we really want it. It's sticky and always visible on the left) 
- Questions/Feedback? Email ccdl@alxeslemonade.org [ or another preferred method]

**Comment by jaclyn-taroni** [comment]
Closed by #56
