### ISSUE TITLE
Update species compendia section 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#70]
https://github.com/AlexsLemonade/refinebio/issues/508#issuecomment-435879283

**Comment by dvenprasad** [comment]
![docs-species-compendia](https://user-images.githubusercontent.com/15315514/48498088-72995f00-e803-11e8-8832-3a9024748431.png)

**Comment by jaclyn-taroni** [comment]
Depends on
