### ISSUE TITLE
Update RNA-seq section to reflect named pipe solution

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#76]
Here's what we say about obtaining raw RNA-seq data currently:

> We obtain sra files run on our supported short-read platforms from NCBI Sequence Read Archive and use fasterq-dump (with default behavior) to obtain fastq files for use with Salmon. Note that any unmated reads from paired experiments are discarded. 

Changes that were introduced in https://github.com/AlexsLemonade/refinebio/pull/1106 should be documented and replace the above text.

**Comment by cgreene** [comment]
> We obtain sra files run on our supported short-read platforms from NCBI Sequence Read Archive. We use fastq-dump (with default behavior) to named pipes, which allows us to support paired-end experiments, and pass these to Salmon. Note that any unmated reads from paired experiments are discarded.

**Comment by jaclyn-taroni** [comment]
Not sure about the 
> (with default behavior) 
bit @cgreene

**Comment by cgreene** [comment]
Nothing fancy - the named pipes bit (see a bit further down) shouldn't affect the output: 
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/salmon.py#L718

**Comment by jaclyn-taroni** [comment]
I'm more concerned with the paired end solution. Specifically, splitting files and using read IDs (see [this reference](https://edwards.sdsu.edu/research/fastq-dump/)).

https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/salmon.py#L741

I think getting into this is "in the weeds," so I was planning on taking "with default behavior" out.

**Comment by cgreene** [comment]
Sounds fine 👍
