### ISSUE TITLE
FAQ: Are refine.bio datasets I download batch corrected?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#82]
I believe @dvenprasad brought something up along these lines earlier this week when we were talking about batch correction (https://github.com/AlexsLemonade/refinebio-examples/issues/24). @dvenprasad can you provide a little more information about what you were thinking?

**Comment by dvenprasad** [comment]
Batch correction related question came up during testing. Users wanted to know whether the datasets they receive were batch corrected or if they would have to account for that in their downstream analysis. 

Something along this line would be more appropriate: 
`Are refine.bio datasets I download batch corrected?`
