### ISSUE TITLE
Updates to account for option to skip QN for individual RNA-seq experiments 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-docs#95]
Related to: https://github.com/AlexsLemonade/refinebio/issues/1285, https://github.com/AlexsLemonade/refinebio/issues/1232, backend ticket about including this information in the `aggregated_metadata.json` file forthcoming 

We will need to:
- Update the downloadable files section. Specifically, we should mention the `aggregate_by`, `scale_by` and whatever we end up using for this in any discussion of `aggregated_metadata.json`
- Update the Contents section of "Getting Started with a refine.bio dataset"
- Update Processing Information > Transformations > Quantile Normalization section to reflect when it is optional
- Add an FAQ about this - this is where the tool tip ? will link to

**Comment by jaclyn-taroni** [comment]
We'll need to add a new link on the front end for `Learn More` cc @dvenprasad @arielsvn

**Comment by dvenprasad** [comment]
I think the link already exists, it just needs to be linked this section in the docs once it is added.

**Comment by jaclyn-taroni** [comment]
@dvenprasad what is an appropriate question for the FAQ? 
> What does it mean to skip quantile normalization for RNA-seq samples?
